repository:
  name: cookiecutter-python
  description: Cookiecutter python template based on nix
  homepage: https://github.com/cdubos-fr/cookiecutter-python
  topics: github, probot
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - name: bug
    color: CC0000
    description: An issue with the system 🐛.

  - name: feature
    color: '#336699'
    description: New functionality.

branches:
  - name: main
    protection:
      required_pull_request_reviews:
      required_status_checks:
        strict: true
        contexts: [
          "Check build (3.10, False)",
          "Check build (3.10, True)",
          "Check build (3.11, False)",
          "Check build (3.11, True)",
          "Check build (3.12, False)",
          "Check build (3.12, True)",
          "Check build (3.13", False)",
          "Check build (3.13, True)",
        ]
      enforce_admins: true
      required_linear_history: true
      restrictions:
