[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
version_files = [
    "cz.toml:version",
    "flake.nix",
    {% if not cookiecutter.is_file_module -%}"{{cookiecutter.project_slug}}.py"{% else %}"{{cookiecutter.project_slug}}/__init__.py"{%- endif %}
]
style = [
    ["qmark", "fg:#ff9d00 bold"],
    ["question", "bold"],
    ["answer", "fg:#ff9d00 bold"],
    ["pointer", "fg:#ff9d00 bold"],
    ["highlighted", "fg:#ff9d00 bold"],
    ["selected", "fg:#cc5454"],
    ["separator", "fg:#cc5454"],
    ["instruction", ""],
    ["text", ""],
    ["disabled", "fg:#858585 italic"]
]
