name: quality-gate
on:
  push:
    branches:
    - develop
    - main
    - release
    tags:
    - "v*"
  pull_request:
    branches:
    - develop
    - main
    - release

jobs:
  code-quality:
    runs-on: self-hosted
    strategy:
      fail-fast: false

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Configure python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install tox dependencies
      run: pip install tox-gh

    - name: Setup tests suites
      run: tox -vv --notest

    - name: Run test suite
      run: tox --skip-pkg-install
      env:
        PYTEST_ADDOPTS: "-vv --durations=10"
