name: Check template build
on:
  push:


jobs:
  check-build:
    name: Check build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        is-file-module: ["False", "True"]
    steps:
      - uses: cachix/install-nix-action@v27
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Install project dependencies
        run: pip install cookiecutter

      - name: Build
        run: |
          cookiecutter --no-input . \
            is_file_module=${{matrix.is-file-module}} \
            project_name=a-module \
            python_version=${{matrix.python-version}}

      - name: Check Install
        run: pip install -e "a-module[dev]"

      - name: Check Nix environments
        run: |
          ls -la a-module
          nix flake check --all-systems --impure path:a-module

      - name: Check project CI
        run: nix develop path:a-module#ci --command tox --root ./a-module -c ./a-module/tox.ini
