name: check-build
on:
  push:


jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install project dependencies
        run: pip install cookiecutter

      - name: Build as file-module
        run: |
          cookiecutter --no-input . \
            is_file_module=true \
            project_name=as-file-module \
          && pip install -e "as-file-module[dev]"

      - name: Build as folder-module
        run: |
          cookiecutter --no-input . \
            is_file_module=false \
            project_name=as-folder-module \
          && pip install -e "as-folder-module[dev]"
