name: Template generation self-check
on:
  push:
  pull_request:

jobs:
  generate-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
        is-file-module: ["False", "True"]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
            uv.lock
            tox.ini
      - run: uv tool install tox --with tox-gh --with tox-uv
      - run: uv tool install cookiecutter
      - name: Generate project from template
        run: |
          cookiecutter --no-input $GITHUB_WORKSPACE \
            is_file_module=${{ matrix.is-file-module }} \
            project_name=a-module \
            python_version=${{ matrix.python-version }}
      - name: Run tox environments (tests, typing, docs)
        working-directory: ./a-module
        run: tox
      - name: Build package
        working-directory: ./a-module
        run: uv build .
      - name: Artifact dist
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: generated-${{ matrix.python-version }}-${{ matrix.is-file-module }}
          path: a-module/dist/
