name: Check template build
on:
  push:


jobs:
  check-build:
    name: Check build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        is-file-module: ["False", "True"]
    steps:
      - uses: cachix/install-nix-action@v27

      - name: Configure python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Install project dependencies
        run: pip install cookiecutter

      - name: Build
        run: |
          cookiecutter --no-input https://github.com/$GITHUB_REPOSITORY.git \
            --checkout $GITHUB_REF_NAME \
            is_file_module=${{matrix.is-file-module}} \
            project_name=a-module \
            python_version=${{matrix.python-version}}

      - name: Use created project as git
        run: |
          git init
          git add .
        working-directory: ./a-module

      - name: Check Nix environments
        run: nix flake check --all-systems --no-write-lock-file --impure
        working-directory: ./a-module

      - name: Lock python deps
        run: nix develop --no-write-lock-file --impure --command just lock
        working-directory: ./a-module

      - name: Check project CI
        run: nix develop .#ci --no-write-lock-file --impure --command tox
        working-directory: ./a-module

      - name: Check development env
        run: nix develop --no-write-lock-file --impure --command echo "🎉 Development environment OK"
        working-directory: ./a-module
