name: Template generation self-check
on:
  push:
  pull_request:

jobs:
  generate-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        is-file-module: ["False", "True"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install cookiecutter
        run: pip install cookiecutter tox tox-pdm
      - name: Generate project from template
        run: |
          cookiecutter --no-input $GITHUB_WORKSPACE \
            is_file_module=${{ matrix.is-file-module }} \
            project_name=a-module \
            python_version=${{ matrix.python-version }}
      - name: Run tox environments (tests, typing, docs)
        working-directory: ./a-module
        run: tox -e tests -e typing -e docs
      - name: Build package
        working-directory: ./a-module
        run: python -m build
      - name: Artifact dist
        uses: actions/upload-artifact@v4
        with:
          name: generated-${{ matrix.python-version }}-${{ matrix.is-file-module }}
          path: a-module/dist/
